/**
 * Índice de componentes do dashboard
 */

export { KPICard } from './KPICard'
export { PlatformPerformanceTable } from './PlatformPerformanceTable'
export { StoreTabs } from './StoreTabs'
export { TripleWhaleKPI } from './TripleWhaleKPI'
export { DateFilter } from './DateFilter'
export { RevenueChart } from './RevenueChart'
export { OrdersChart } from './OrdersChart'
export { PlatformROASChart } from './PlatformROASChart'
export { RevenueDistributionChart } from './RevenueDistributionChart'
export { PlatformFilter } from './PlatformFilter'
export { StoreDropdown } from './StoreDropdown'
export { PlatformDropdown } from './PlatformDropdown'
export { QuickInsights } from './QuickInsights'
export { PeriodComparison } from './PeriodComparison'
export { TargetsProgress } from './TargetsProgress'
export { PlatformRanking } from './PlatformRanking'
export { BudgetTracking } from './BudgetTracking'
export { PerformanceHeatmap } from './PerformanceHeatmap'
export { Opportunities } from './Opportunities'
export { RecentChanges } from './RecentChanges'
export { QuickActions } from './QuickActions'
export { CampaignTreemap } from './CampaignTreemap'
export { QuickSuggestions } from './QuickSuggestions'
export { IntegrationAlert } from './IntegrationAlert'
export { CustomerReturnRateKPI } from './CustomerReturnRateKPI'
export { SalesSources } from './SalesSources'
export { AcquisitionSourceFilter } from './AcquisitionSourceFilter'
